### ISSUE TITLE
Benchmarking of cascaded flight servers

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/arrow-data-plane#16]
@cdoron to edit with plan details

**Comment by the-mesh-for-data** [comment]
Different options we can test:
1. The relay flight server is on the same machine as the "main" flight server / different machines
2. test on baremetal / k8s containers
3. Relay server performs no transformation / transformation (currently no transformation)
4. no transformation: with WASM memory allocation and without
5. with transformation: Java transformation / WASM transformation
6. different datasets. Currently we are testing with an in-memory dataset consisting of a single record batch sent a 1000 times
